---
title: "House Price Precictions R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
  word_document: default
---

# load libraries
```{r}
library(knitr)
library(ggplot2)
library(plyr)
library(dplyr)
library(corrplot)
library(gridExtra)
library(scales)
library(Rmisc)
library(ggrepel)
library(randomForest)
library(psych)
library(xgboost)
```

# Read Train and Test data

```{r}
train <- read.csv("train.csv", stringsAsFactors = F)
test <- read.csv("test.csv", stringsAsFactors = F)
```

```{r}
dim(train)
str(train[,c(1:10, 81)])
# #Getting rid of the IDs but keeping the test IDs in a vector. These are needed to compose the submission file
test_labels <- test$Id
test$Id <- NULL
train$Id <- NULL
```
```{r}
test$SalePrice <- NA
all <- rbind(train, test)
dim(all)
```
## Exploring some of the most important variables
```{r}
ggplot(data = all[!is.na(all$SalePrice),], aes(x = SalePrice))+
  geom_histogram(fill = "blue", binwidth = 10000)+
  scale_x_continuous(breaks = seq(0, 800000, by = 100000), labels = comma)
```
```{r}
summary(all$SalePrice)
```

### The character variables need some work before I can use them. To get a feel for the dataset, I decided to first see which numeric variables have a high correlation with the SalePrice.
### Correlations with SalePrice

```{r}
#index vector numeric variables
numericVars <- which(sapply(all, is.numeric))
#saving names vector for use later on
numericNames <- names(numericVars)
## There are 37 numeric variables
```
```{r}
all_numVar <- all[, numericVars]
#correlations of all numeric variables
cor_numVar <- cor(all_numVar, use = "pairwise.complete.obs")
#sort on decreasing correlations with SalePrice
cor_sorted <- as.matrix(sort(cor_numVar[, 'SalePrice'], decreasing = TRUE))
#select only high corelations
CorHigh <- names(which(apply(cor_sorted, 1, function(x) abs(x) > 0.5)))
cor_numVar <- cor_numVar[CorHigh, CorHigh]

corrplot.mixed(cor_numVar, tl.col = "black", tl.pos = "lt")

```

